DROP TABLE YELP_COMPLIMENTED_FRIENDLIST CASCADE CONSTRAINTS;

DROP TABLE YELP_USER_FRIENDLIST CASCADE CONSTRAINTS;

DROP TABLE YELP_USER CASCADE CONSTRAINTS;

DROP TABLE YELP_LIST_OF_COMMENTS CASCADE CONSTRAINTS;

DROP TABLE YELP_REVIEWS CASCADE CONSTRAINTS;

DROP TABLE YELP_CHECKIN CASCADE CONSTRAINTS;

DROP TABLE YELP_BUSINESS_SUB_CATEGORY CASCADE CONSTRAINTS;

DROP TABLE YELP_BUSINESS_CATEGORY CASCADE CONSTRAINTS;

DROP TABLE YELP_BUSINESS_ADDRESS CASCADE CONSTRAINTS;

DROP TABLE YELP_BUSINESS CASCADE CONSTRAINTS;
