SELECT COUNT(*) FROM YELP_BUSINESS yb JOIN YELP_BUSINESS_CATEGORY Ybc 
ON YB.BUSINESS_CAT_ID = Ybc.BUSINESS_CAT_ID JOIN YELP_BUSINESS_ADDRESS yba 
ON YB.BUSINESS_ID = Yba.BUSINESS_ID 
WHERE ybc.BUSINESS_CAT_NAME = 'National Parks' AND state = 'AZ';