SELECT * FROM YELP_USER WHERE  YELP_USER_ID IN 
(SELECT YELP_USER_ID FROM   YELP_LIST_OF_COMMENTS
HAVING COUNT(*) >= 2 
GROUP  BY YELP_USER_ID) AND YELP_USER_ID NOT IN 
(SELECT AUTHOR FROM YELP_REVIEWS); 