SELECT * FROM YELP_USER yu JOIN YELP_COMPLIMENTED_FRIENDLIST ycf ON
yu.YELP_USER_ID = ycf.YELP_USER_ID AND yu.GENDER = 'M' AND ycf.YELP_FRIEND_ID IN 
(SELECT yelp_user_id FROM YELP_USER WHERE Gender = 'F');