SELECT YR.BUSINESS_ID, YB.BUSINESS_NAME, COUNT(*) AS NO_OF_REVIEWS, AVG(YR.NO_OF_STARS) 
FROM   (SELECT * FROM   YELP_REVIEWS WHERE  NO_OF_STARS = 5) YR JOIN 
(SELECT * FROM   YELP_USER WHERE  TRUNC(SYSDATE - DOB) / 365 > 20 
AND TRUNC(SYSDATE - DOB) / 365 <= 25) YU 
ON YR.AUTHOR = YU.YELP_USER_ID JOIN 
(SELECT * FROM   YELP_BUSINESS) YB 
ON YR.BUSINESS_ID = YB.BUSINESS_ID 
GROUP  BY YR.BUSINESS_ID, YB.BUSINESS_NAME 
ORDER  BY NO_OF_REVIEWS, TO_NUMBER(SUBSTR(YR.BUSINESS_ID, 2)) ASC; 


