SELECT BUSINESS_ID, COUNT(*) AS NO_OF_CHECKINS FROM YELP_CHECKIN
WHERE BUSINESS_ID IN
(SELECT TAB1.BUSINESS_ID FROM (SELECT BUSINESS_ID , AVG(NO_OF_STARS) AS AVERAGEPREV FROM YELP_REVIEWS
    WHERE TRUNC(PUBLISH_DATE) >= TO_DATE('05/01/2015','MM/dd/yyyy') AND 
        TRUNC(PUBLISH_DATE)    < TO_DATE('06/01/2015','MM/dd/yyyy')
    GROUP BY BUSINESS_ID
    )TAB1
JOIN
(SELECT BUSINESS_ID, AVG(NO_OF_STARS) AS AVERAGE FROM YELP_REVIEWS WHERE 
 TRUNC(PUBLISH_DATE) >= TO_DATE('06/01/2015','MM/dd/yyyy') AND 
 TRUNC(PUBLISH_DATE)    < TO_DATE('07/01/2015','MM/dd/yyyy')
GROUP BY BUSINESS_ID) TAB2
ON TAB1.BUSINESS_ID = TAB2.BUSINESS_ID WHERE 
AVERAGE = 2 * AVERAGEPREV
  )
GROUP BY BUSINESS_ID;